### ISSUE TITLE
Workflow setup_environment.sh path issue

### ISSUE THREAD

**Issue by vlasticn** [structr/structr-deploy-action#1]
Hi, we encounetered an issue during actions workflow:
`Run structr/structr-deploy-action@v1
  with:
    structr-version: 4.2.0
    neo4j-version: 4.4
    structr-webapp-path: /home/runner/work/structr_usage/structr_usage/webapp
Run echo "Running Structr:4.2.0 with Neo4j:4.4 and deploying from /home/runner/work/structr_usage/structr_usage/webapp"
  echo "Running Structr:4.2.0 with Neo4j:4.4 and deploying from /home/runner/work/structr_usage/structr_usage/webapp"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Running Structr:4.2.0 with Neo4j:4.4 and deploying from /home/runner/work/structr_usage/structr_usage/webapp
Run ./setup_environment.sh /home/runner/work/_actions/structr/structr-deploy-action/v1 && cd /home/runner/work/_actions/structr/structr-deploy-action/v1 && docker-compose up -d      
  ./setup_environment.sh /home/runner/work/_actions/structr/structr-deploy-action/v1 && cd /home/runner/work/_actions/structr/structr-deploy-action/v1 && docker-compose up -d      
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NEO4j_VERSION: 4.4
    STRUCTR_VERSION: 4.2.0
    STRUCTR_WEBAPP_PATH: /home/runner/work/structr_usage/structr_usage/webapp
    STRUCTR_LICENSE: 
    STRUCTR_CONF_FILE: 
/home/runner/work/_temp/e5adeaf0-43c9-41b1-b4a2-8948899063f1.sh: line 1: ./setup_environment.sh: No such file or directory
Error: Process completed with exit code 127.`

Workflow file: 

`name: Test deployment

on:
  workflow_dispatch

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    name: Deploy and test
    steps:
      - uses: actions/checkout@v3
      - id: Test
        uses: structr/structr-deploy-action@v1`

This seems to be related with the latest chage in actions.yml file line 45 and 46. 
It seems to miss cd ${{ github.action_path }} before script execution.

**Comment by derkaiserreich** [comment]
Thanks for reporting this. It seems that there was missing a cd into the actions directory for accessing the shell script file.

@vlasticn Can you please try and re-run the action again? It should work fine again now.
