### ISSUE TITLE
Issue with running  structr-deploy-actionv1

### ISSUE THREAD

**Issue by vbejatovic-pdy** [structr/structr-deploy-action#2]
Hi, we can't run action anymore it is during creating of v1_structr_1. Have there been any changes?

Here is the log:

`39s
Run structr/structr-deploy-action@v[1](https://github.com/Suhling-Tooling/sta-backend-structr/actions/runs/4545648043/jobs/8013271011#step:5:1)
Run echo "Running Structr:4.2.3 with Neo4j:4.4 and deploying from /home/runner/work/sta-backend-structr/sta-backend-structr/webapp"
Running Structr:4.2.3 with Neo4j:4.4 and deploying from /home/runner/work/sta-backend-structr/sta-backend-structr/webapp
Run cd /home/runner/work/_actions/structr/structr-deploy-action/v1 && ./setup_environment.sh /home/runner/work/_actions/structr/structr-deploy-action/v1 && docker-compose up -d
Replacing variables for Structr and Neo4j docker configuration
Creating network "v1_database" with the default driver
Pulling neo4j (neo4j:4.4)...
4.4: Pulling from library/neo4j
Digest: sha25[6](https://github.com/Suhling-Tooling/sta-backend-structr/actions/runs/4545648043/jobs/8013271011#step:5:7):5fd30c52a8c347334641ea62[9](https://github.com/Suhling-Tooling/sta-backend-structr/actions/runs/4545648043/jobs/8013271011#step:5:11)54a420[10](https://github.com/Suhling-Tooling/sta-backend-structr/actions/runs/4545648043/jobs/8013271011#step:5:12)4b40253535a8018ec3cc91fb0713c9b
Status: Downloaded newer image for neo4j:4.4
Pulling structr (structr/structr:4.2.3)...
4.2.3: Pulling from structr/structr
Digest: sha256:c2a283d6eb1a[23](https://github.com/Suhling-Tooling/sta-backend-structr/actions/runs/4545648043/jobs/8013271011#step:5:26)d70ea4748058a62b297e9a8eb9890163435fc753579f341e1e
Status: Downloaded newer image for structr/structr:4.2.3
Creating v1_neo4j_1 ... 
Creating v1_neo4j_1 ... done
Creating v1_structr_1 ... 
Creating v1_structr_1 ... error

ERROR: for v1_structr_1  Cannot create container for service structr: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for structr  Cannot create container for service structr: create .: volume name is too short, names should be at least two alphanumeric characters
Encountered errors while bringing up the project.
Error: Process completed with exit code 1.`

Thank you in advance,
Vanja

**Comment by derkaiserreich** [comment]
@vbejatovic-pdy There was an error in a recent change that was made to the action. The Issue should be fixed.

**Comment by vbejatovic-pdy** [comment]
@derkaiserreich,

Thank you very much, I can confirm that it's working now.
